---

  # BOOTSTRAP
  - name: rke2 boostrap initial server node
    ansible.builtin.shell: "{{ k8s_install_script }}"
    environment: "{{ k8s_env | combine({'INSTALL_RKE2_TYPE': 'server'}) }}"
    when:
      - k8s_node_type == "bootstrap"

  - name: rke2 template cni manifests
    ansible.builtin.template:
      src: "templates/{{ k8s_type }}-{{ k8s_cni_type }}-config.yaml.j2"
      dest: "{{ k8s_manifests_path }}/{{ k8s_type }}-{{ k8s_cni_type }}-config.yaml"
      mode: 0600
    when:
      - k8s_node_type == "bootstrap"

  - name: rke2 start bootstrap node
    ansible.builtin.include_tasks: start.yml
    when:
      - k8s_node_type == "bootstrap"

  # ADD SERVERS
  - name: rke2 add additional server nodes
    ansible.builtin.shell: "{{ k8s_install_script }}"
    environment: "{{ k8s_env | combine({'INSTALL_RKE2_TYPE': 'server'}) }}"
    when:
      - k8s_node_type == "server"

  # ADD AGENTS
  - name: rke2 add agent nodes
    ansible.builtin.shell: "{{ k8s_install_script }}"
    environment: "{{ k8s_env | combine({'INSTALL_RKE2_TYPE': 'agent'}) }}"
    when:
      - k8s_node_type == "agent"

  # POST-DEPLOY
  - name: rke2 start additional nodes
    ansible.builtin.include_tasks: start.yml
    when:
      - k8s_node_type != "bootstrap"
